# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4dfd8078a9f1d7781b1f2ad298ab32a961d71b9097459ddd8df09360525bdf7661589e74ab54824a38b737578e4208c1a92afc7ff8c5d8c8d57d112fd144249

  twitter_api_key: PPVzPT2eaC5yA0tNU7cOGFoQB
  twitter_api_secret: TRsaO3Vn26LsyUJu2cZzvcwv0SdVNusgo9tzqCxtzciHZvG7jK

  twitter_token: 40179636-QbCrikOKheasmcTjYAIZNNO3oXkalg8tGnCITJRe5
  twitter_token_secret: 22eCgeu77gQLwi45TwguhRq0UjekDmKUzwITixCyg9Hec

test:
  secret_key_base: 6ac937f70d866618e9ded44b5c2fd1ffc55b9a224af4b2db89b5a61a2000a440ef93d0774537617c540832a25c013ba2a9b14020fe222a0c7c1ed833863be818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
